
services:

  search-vectorfaces-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/public:/usr/share/nginx/html
      - ./tmp/uploads:/home/vectorfaces/uploads:ro
    ports:
      - "16700:80"
    
    restart: unless-stopped
    depends_on:
      search-vectorfaces-backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-s", "http://vectorfaces-backend:8000/stats", "|", "grep", "-q", '"status":"running"', "||", "exit", "1"]
      interval: 5s
      timeout: 5s
      retries: 25
      start_period: 30s

  
  search-vectorfaces-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/app
      - ./tmp/tmp:/home/vectorfaces/tmp
      - ./tmp/.insightface:/home/vectorfaces/.insightface
      - ./tmp/uploads:/home/vectorfaces/uploads
    ports:
      - "8000:8000"
    env_file:
      - env.local
    restart: unless-stopped
